'^git@github.com:(.*?)(\.git)?$': 'http://github.com/#{$1}/commit/#{commit}'
'^git://github.com/(.*?)(\.git)?$': 'http://github.com/#{$1}/commit/#{commit}'
'^http://github.com/(.*?)(\.git)?$': 'http://github.com/#{$1}/commit/#{commit}'
